config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]
  resource :session, controller: "clearance/sessions", only: [ :create ]

  resources :users, only: [ :create ] do
    resource :password,
      controller: "clearance/passwords",
      only: [ :edit, :update ]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  resources :articles do
    resources :comments
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/broadcast/comment.rb
module Broadcast
  class Comment
    def self.append(comment:)
      new(comment).append
    end

    def self.remove(comment:)
      new(comment).remove
    end

    def initialize(comment)
      @comment = comment
    end

    def append
      Turbo::StreamsChannel.broadcast_append_later_to(
        :comments,
      target: "comments",
        html: rendered_component
      )
    end

    def remove
      Turbo::StreamsChannel.broadcast_remove_to(
      :comments,
      target: "comment_#{@comment.id}"
      )
    end

    private

    attr_reader :comment

    def rendered_component
      ApplicationController.render(
        Comments::CommentComponent.new(comment: comment),
        layout: false
      )
    end

  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :user
  belongs_to :article

  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
  
  class_methods do
    def public_count
      where(status: "public").count
    end
  end

  def archived?
    status == "archived"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit::Authorization
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:error] = "Sorry, you don't have permission to do that"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login
  before_action :set_article, only: %i[edit update destroy]

  def index
    @articles = policy_scope(Article).all
  end

  def show
    authorize @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @user = User.find(current_user.id)
    @article = @user.articles.create(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def my_debugger
    # this is my own debugger method
    debugger
  end

  def set_article
    @article = authorize Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [ :destroy, :create ]
  def create
    @article = Article.find(params[:article_id])

    # Use for Turbo streams if not broadcasting
    # @comment = @article.comments.create(comment_params.merge({ user: current_user }))

    # Broadcasting the new comments
    @comment = @article.comments.new(comment_params.merge({ user: current_user }))

    if @comment.save
      Broadcast::Comment.append(comment: @comment)
    end
    # This seems to break the broadcasting
    # respond_to do |format|
    #   format.html { redirect_to article_comments_path }
    #   format.turbo_stream
    # end

    # redirect_to article_path(@article)
  end


  def destroy
    @article = Article.find(params[:article_id])
    @comment = authorize @article.comments.find(params[:id])

    if @comment.destroy
      Broadcast::Comment.remove(comment: @comment)
    end

    #This is for the normal Turbo streams
    # @comment.destroy
    #
    # respond_to do |format|
    #   format.turbo_stream { render turbo_stream: turbo_stream.remove(@comment) }
    #   format.html { redirect_to article_comments_path }
    # end
    # redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = policy_scope(Article).all
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || "public" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render Articles::IndexComponent.new(articles: @articles) %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="h-full">
  <%= turbo_stream_from :comments %>
  <%= render(Articles::ArticleComponent.new(article: @article)) %>

<!--  <turbo-frame id="comments">-->
<div id="comments">
    <h2 class="mt-6 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Comments</h2>
    <% if policy_scope(@article.comments).empty? %>
      <p class="mt-3">Be the first to  write a comment!</p>
    <% else %>
      <%= render(Comments::CommentComponent.with_collection(policy_scope(@article.comments))) %>
    <% end %>
</div>
    <h2 class="mt-6 text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl">Add a comment</h2>
    <div id="comments_form">
      <%= render(Comments::FormComponent.new(article: @article)) %>
    </div>
<!--  </turbo-frame>-->
  <p class="m-4">The page was loaded at: <%= Time.now.strftime("%k:%M:%S") %></p>

</div>

app/views/comments/_comment.html.erb
<% unless @comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= @comment.user.username %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= @comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [@comment.article, @comment], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [article, article.comments.build ] do |form| %>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

    <% @comment.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
    <% end %>



  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: "public" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.replace "comments_form" do %>
  <%= render(Comments::FormComponent.new(article: @article)) %>
<% end %>

<%= turbo_stream.append "comments" do %>
  <%= render Comments::CommentComponent.new(comment: @comment) %>
<% end %>

app/views/home/index.html.erb
<%= render Home::IndexComponent.new(articles: @articles) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title><%= content_for(:title) || "Blogstars" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- not working -->
    <%#= javascript_importmap_tags %>

    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
  </head>

  <body class="h-full">
    <%= render(Navigation::NavbarComponent.new) %>
    <%= render(Flash::FlashComponent.new) %>
    <div class="container mx-auto flex justify-center items-center h-full">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
  <% @user.errors.full_messages_for(:username).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email %>
  <% @user.errors.full_messages_for(:email).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
  <% @user.errors.full_messages_for(:password).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>